### ISSUE TITLE
A typo in 'Handling events' page

### ISSUE THREAD

**Issue by gamtiq** [trivago/melody-web#12]
There is the following line in [Handling events](https://github.com/trivago/melody-web/blob/master/docs/docs/quickstart/events.md) page:
```js
const enhancers = compose(withTickingCounter, withClickHandlers);
```
But `withTickingCounter` is not defined. It seems there should be `withIncreasingCounter`.

**Comment by pago** [comment]
Thanks for reporting this! Would you mind opening a PR with the fix?
