### ISSUE TITLE
yarn.lock containing inaccessible resolve urls

### ISSUE THREAD

**Issue by Robbilie** [trivago/melody-web#3]
the yarn.lock file contains links to what seems to be an internal npm cache (http://npm.pkg.trivago.trv:8080), when cloning the repository installing the pinned packages obviously does not work

**Comment by Robbilie** [comment]
same goes for the .yarnrc file…
im not sure if you want public contributions in this repo so i guess you could keep your internal registry in these files

**Comment by Robbilie** [comment]
pulling from the official npm repos yields problems with the versions since there are higher ones available internally

**Comment by jamesb3ll** [comment]
Thanks, I've removed the `.yarnrc` and updated the lock file. Also the github page is now served from the `docs/` folder.
