### ISSUE TITLE
create-melody-app repo not public

### ISSUE THREAD

**Issue by Robbilie** [trivago/melody-web#4]
probably just not yet but the https://github.com/trivago/create-melody-app repo required to create a new melody app is not there

**Comment by Robbilie** [comment]
on that note, without running `yarn global add create-melody-app` the nice and short commands seen on the page wont work so it might be worth mentioning that you have to run that command first

**Comment by jamesb3ll** [comment]
`create-melody-app` is now public at https://github.com/trivago/create-melody-app
According to the docs `yarn create` should install and run the executable:
https://yarnpkg.com/lang/en/docs/cli/create/

**Comment by Robbilie** [comment]
yeah missing repo and then running an ancient version of yarn caused this for me ^^
